execute at @e[tag=backpack_black_claim,hasitem={item=item:backpack_black,location=slot.weapon.mainhand}] run tp @e[tag=!grounded,type=entity:backpack_inventory_black] ^^1.5^
execute at @e[tag=backpack_black_claim] run tp @e[tag=!grounded,type=entity:backpack_inventory_black] ^^9^
execute at @e[tag=backpack_blue_claim,hasitem={item=item:backpack_blue,location=slot.weapon.mainhand}] run tp @e[tag=!grounded,type=entity:backpack_inventory_blue] ^^1.5^
execute at @e[tag=backpack_blue_claim] run tp @e[tag=!grounded,type=entity:backpack_inventory_blue] ^^9^
execute at @e[tag=backpack_brown_claim,hasitem={item=item:backpack_brown,location=slot.weapon.mainhand}] run tp @e[tag=!grounded,type=entity:backpack_inventory_brown] ^^1.5^
execute at @e[tag=backpack_brown_claim] run tp @e[tag=!grounded,type=entity:backpack_inventory_brown] ^^9^
execute at @e[tag=backpack_cyan_claim,hasitem={item=item:backpack_cyan,location=slot.weapon.mainhand}] run tp @e[tag=!grounded,type=entity:backpack_inventory_cyan] ^^1.5^
execute at @e[tag=backpack_cyan_claim] run tp @e[tag=!grounded,type=entity:backpack_inventory_cyan] ^^9^
execute at @e[tag=backpack_gray_claim,hasitem={item=item:backpack_gray,location=slot.weapon.mainhand}] run tp @e[tag=!grounded,type=entity:backpack_inventory_gray] ^^1.5^
execute at @e[tag=backpack_gray_claim] run tp @e[tag=!grounded,type=entity:backpack_inventory_gray] ^^9^
execute at @e[tag=backpack_green_claim,hasitem={item=item:backpack_green,location=slot.weapon.mainhand}] run tp @e[tag=!grounded,type=entity:backpack_inventory_green] ^^1.5^
execute at @e[tag=backpack_green_claim] run tp @e[tag=!grounded,type=entity:backpack_inventory_green] ^^9^
execute at @e[tag=backpack_light_blue_claim,hasitem={item=item:backpack_light_blue,location=slot.weapon.mainhand}] run tp @e[tag=!grounded,type=entity:backpack_inventory_light_blue] ^^1.5^
execute at @e[tag=backpack_light_blue_claim] run tp @e[tag=!grounded,type=entity:backpack_inventory_light_blue] ^^9^
execute at @e[tag=backpack_lime_claim,hasitem={item=item:backpack_lime,location=slot.weapon.mainhand}] run tp @e[tag=!grounded,type=entity:backpack_inventory_lime] ^^1.5^
execute at @e[tag=backpack_lime_claim] run tp @e[tag=!grounded,type=entity:backpack_inventory_lime] ^^9^
execute at @e[tag=backpack_magenta_claim,hasitem={item=item:backpack_magenta,location=slot.weapon.mainhand}] run tp @e[tag=!grounded,type=entity:backpack_inventory_magenta] ^^1.5^
execute at @e[tag=backpack_magenta_claim] run tp @e[tag=!grounded,type=entity:backpack_inventory_magenta] ^^9^
execute at @e[tag=backpack_purple_claim,hasitem={item=item:backpack_purple,location=slot.weapon.mainhand}] run tp @e[tag=!grounded,type=entity:backpack_inventory_purple] ^^1.5^
execute at @e[tag=backpack_purple_claim] run tp @e[tag=!grounded,type=entity:backpack_inventory_purple] ^^9^
execute at @e[tag=backpack_orange_claim,hasitem={item=item:backpack_orange,location=slot.weapon.mainhand}] run tp @e[tag=!grounded,type=entity:backpack_inventory_orange] ^^1.5^
execute at @e[tag=backpack_orange_claim] run tp @e[tag=!grounded,type=entity:backpack_inventory_orange] ^^9^
execute at @e[tag=backpack_pink_claim,hasitem={item=item:backpack_pink,location=slot.weapon.mainhand}] run tp @e[tag=!grounded,type=entity:backpack_inventory_pink] ^^1.5^
execute at @e[tag=backpack_pink_claim] run tp @e[tag=!grounded,type=entity:backpack_inventory_pink] ^^9^
execute at @e[tag=backpack_red_claim,hasitem={item=item:backpack_red,location=slot.weapon.mainhand}] run tp @e[tag=!grounded,type=entity:backpack_inventory_red] ^^1.5^
execute at @e[tag=backpack_red_claim] run tp @e[tag=!grounded,type=entity:backpack_inventory_red] ^^9^
execute at @e[tag=backpack_silver_claim,hasitem={item=item:backpack_silver,location=slot.weapon.mainhand}] run tp @e[tag=!grounded,type=entity:backpack_inventory_silver] ^^1.5^
execute at @e[tag=backpack_silver_claim] run tp @e[tag=!grounded,type=entity:backpack_inventory_silver] ^^9^
execute at @e[tag=backpack_white_claim,hasitem={item=item:backpack_white,location=slot.weapon.mainhand}] run tp @e[tag=!grounded,type=entity:backpack_inventory_white] ^^1.5^
execute at @e[tag=backpack_white_claim] run tp @e[tag=!grounded,type=entity:backpack_inventory_white] ^^9^
execute at @e[tag=backpack_yellow_claim,hasitem={item=item:backpack_yellow,location=slot.weapon.mainhand}] run tp @e[tag=!grounded,type=entity:backpack_inventory_yellow] ^^1.5^
execute at @e[tag=backpack_yellow_claim] run tp @e[tag=!grounded,type=entity:backpack_inventory_yellow] ^^9^
execute at @e[tag=backpack_leather_claim,hasitem={item=item:backpack_leather,location=slot.weapon.mainhand}] run tp @e[tag=!grounded,type=entity:backpack_inventory_leather] ^^1.5^
execute at @e[tag=backpack_leather_claim] run tp @e[tag=!grounded,type=entity:backpack_inventory_leather] ^^9^